### GET request to example server
GET http://localhost:3000/api/user

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name":"giorgi",
    "email":"giorgi",
    "password":"giorgi",
    "profileImage":"giorgi"
}